package com.cisco.la.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoldenSampleModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public GoldenSampleModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNameIsNull() {
            addCriterion("smpl_name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("smpl_name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("smpl_name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("smpl_name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("smpl_name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("smpl_name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("smpl_name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("smpl_name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("smpl_name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("smpl_name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("smpl_name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("smpl_name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("smpl_name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("smpl_name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("smpl_role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("smpl_role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("smpl_role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("smpl_role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("smpl_role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("smpl_role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("smpl_role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("smpl_role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("smpl_role like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("smpl_role not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("smpl_role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("smpl_role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("smpl_role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("smpl_role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("smpl_rl_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("smpl_rl_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("smpl_rl_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("smpl_rl_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("smpl_rl_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("smpl_rl_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("smpl_rl_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("smpl_rl_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("smpl_rl_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("smpl_rl_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("smpl_rl_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("smpl_rl_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("smpl_rl_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("smpl_rl_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andMandatoryIsNull() {
            addCriterion("smpl_mandatory is null");
            return (Criteria) this;
        }

        public Criteria andMandatoryIsNotNull() {
            addCriterion("smpl_mandatory is not null");
            return (Criteria) this;
        }

        public Criteria andMandatoryEqualTo(String value) {
            addCriterion("smpl_mandatory =", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryNotEqualTo(String value) {
            addCriterion("smpl_mandatory <>", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryGreaterThan(String value) {
            addCriterion("smpl_mandatory >", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryGreaterThanOrEqualTo(String value) {
            addCriterion("smpl_mandatory >=", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryLessThan(String value) {
            addCriterion("smpl_mandatory <", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryLessThanOrEqualTo(String value) {
            addCriterion("smpl_mandatory <=", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryLike(String value) {
            addCriterion("smpl_mandatory like", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryNotLike(String value) {
            addCriterion("smpl_mandatory not like", value, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryIn(List<String> values) {
            addCriterion("smpl_mandatory in", values, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryNotIn(List<String> values) {
            addCriterion("smpl_mandatory not in", values, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryBetween(String value1, String value2) {
            addCriterion("smpl_mandatory between", value1, value2, "mandatory");
            return (Criteria) this;
        }

        public Criteria andMandatoryNotBetween(String value1, String value2) {
            addCriterion("smpl_mandatory not between", value1, value2, "mandatory");
            return (Criteria) this;
        }

        public Criteria andOptionalIsNull() {
            addCriterion("smpl_optional is null");
            return (Criteria) this;
        }

        public Criteria andOptionalIsNotNull() {
            addCriterion("smpl_optional is not null");
            return (Criteria) this;
        }

        public Criteria andOptionalEqualTo(String value) {
            addCriterion("smpl_optional =", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalNotEqualTo(String value) {
            addCriterion("smpl_optional <>", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalGreaterThan(String value) {
            addCriterion("smpl_optional >", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalGreaterThanOrEqualTo(String value) {
            addCriterion("smpl_optional >=", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalLessThan(String value) {
            addCriterion("smpl_optional <", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalLessThanOrEqualTo(String value) {
            addCriterion("smpl_optional <=", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalLike(String value) {
            addCriterion("smpl_optional like", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalNotLike(String value) {
            addCriterion("smpl_optional not like", value, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalIn(List<String> values) {
            addCriterion("smpl_optional in", values, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalNotIn(List<String> values) {
            addCriterion("smpl_optional not in", values, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalBetween(String value1, String value2) {
            addCriterion("smpl_optional between", value1, value2, "optional");
            return (Criteria) this;
        }

        public Criteria andOptionalNotBetween(String value1, String value2) {
            addCriterion("smpl_optional not between", value1, value2, "optional");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("smpl_update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("smpl_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("smpl_update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("smpl_update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("smpl_update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("smpl_update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("smpl_update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("smpl_update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("smpl_update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("smpl_update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("smpl_update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("smpl_update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("smpl_active is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("smpl_active is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Boolean value) {
            addCriterion("smpl_active =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Boolean value) {
            addCriterion("smpl_active <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Boolean value) {
            addCriterion("smpl_active >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("smpl_active >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Boolean value) {
            addCriterion("smpl_active <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("smpl_active <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Boolean> values) {
            addCriterion("smpl_active in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Boolean> values) {
            addCriterion("smpl_active not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("smpl_active between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("smpl_active not between", value1, value2, "active");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 09 17:12:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_golden_sample
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}