package com.cisco.la.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleHistoryModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public RoleHistoryModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIDIsNull() {
            addCriterion("hstr_usr_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIDIsNotNull() {
            addCriterion("hstr_usr_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIDEqualTo(String value) {
            addCriterion("hstr_usr_id =", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotEqualTo(String value) {
            addCriterion("hstr_usr_id <>", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThan(String value) {
            addCriterion("hstr_usr_id >", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDGreaterThanOrEqualTo(String value) {
            addCriterion("hstr_usr_id >=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThan(String value) {
            addCriterion("hstr_usr_id <", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLessThanOrEqualTo(String value) {
            addCriterion("hstr_usr_id <=", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDLike(String value) {
            addCriterion("hstr_usr_id like", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotLike(String value) {
            addCriterion("hstr_usr_id not like", value, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDIn(List<String> values) {
            addCriterion("hstr_usr_id in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotIn(List<String> values) {
            addCriterion("hstr_usr_id not in", values, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDBetween(String value1, String value2) {
            addCriterion("hstr_usr_id between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andUserIDNotBetween(String value1, String value2) {
            addCriterion("hstr_usr_id not between", value1, value2, "userID");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("hstr_rl_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("hstr_rl_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("hstr_rl_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("hstr_rl_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("hstr_rl_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("hstr_rl_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("hstr_rl_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("hstr_rl_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("hstr_rl_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("hstr_rl_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("hstr_rl_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("hstr_rl_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("hstr_rl_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("hstr_rl_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryIsNull() {
            addCriterion("hstr_rl_history is null");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryIsNotNull() {
            addCriterion("hstr_rl_history is not null");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryEqualTo(String value) {
            addCriterion("hstr_rl_history =", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryNotEqualTo(String value) {
            addCriterion("hstr_rl_history <>", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryGreaterThan(String value) {
            addCriterion("hstr_rl_history >", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("hstr_rl_history >=", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryLessThan(String value) {
            addCriterion("hstr_rl_history <", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryLessThanOrEqualTo(String value) {
            addCriterion("hstr_rl_history <=", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryLike(String value) {
            addCriterion("hstr_rl_history like", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryNotLike(String value) {
            addCriterion("hstr_rl_history not like", value, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryIn(List<String> values) {
            addCriterion("hstr_rl_history in", values, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryNotIn(List<String> values) {
            addCriterion("hstr_rl_history not in", values, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryBetween(String value1, String value2) {
            addCriterion("hstr_rl_history between", value1, value2, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andRoleHistoryNotBetween(String value1, String value2) {
            addCriterion("hstr_rl_history not between", value1, value2, "roleHistory");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("hstr_update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("hstr_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("hstr_update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("hstr_update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("hstr_update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("hstr_update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("hstr_update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("hstr_update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("hstr_update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("hstr_update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("hstr_update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("hstr_update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_rl_history
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 09 17:12:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.la_rl_history
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}