package com.cisco.la.model;

public class UserModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_id
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_budget
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private Double budget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_balance
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_bu
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String bu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_title
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_grade
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_rl_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.la_user.usr_active
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    private Boolean active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_id
     *
     * @return the value of public.la_user.usr_id
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_id
     *
     * @param id the value for public.la_user.usr_id
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_name
     *
     * @return the value of public.la_user.usr_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_name
     *
     * @param name the value for public.la_user.usr_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_budget
     *
     * @return the value of public.la_user.usr_budget
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Double getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_budget
     *
     * @param budget the value for public.la_user.usr_budget
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setBudget(Double budget) {
        this.budget = budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_balance
     *
     * @return the value of public.la_user.usr_balance
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_balance
     *
     * @param balance the value for public.la_user.usr_balance
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_bu
     *
     * @return the value of public.la_user.usr_bu
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getBu() {
        return bu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_bu
     *
     * @param bu the value for public.la_user.usr_bu
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setBu(String bu) {
        this.bu = bu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_title
     *
     * @return the value of public.la_user.usr_title
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_title
     *
     * @param title the value for public.la_user.usr_title
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_grade
     *
     * @return the value of public.la_user.usr_grade
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_grade
     *
     * @param grade the value for public.la_user.usr_grade
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_rl_name
     *
     * @return the value of public.la_user.usr_rl_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_rl_name
     *
     * @param roleName the value for public.la_user.usr_rl_name
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.la_user.usr_active
     *
     * @return the value of public.la_user.usr_active
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.la_user.usr_active
     *
     * @param active the value for public.la_user.usr_active
     *
     * @mbg.generated Tue Jan 09 17:12:26 CST 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }
}